context:
  name: easydiffraction
  version: "0.4.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easydiffraction-${{ version }}.tar.gz
  sha256: f22c0a61071a0d6ab74e949128646be2b30e1a38f27cdda9da431a61480a4730

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }},<3.13
    - cryspy
    - easycrystallography
    - easyscience
    - pooch

tests:
  - python:
      imports:
        - easydiffraction
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  homepage: https://easydiffraction.org/
  summary: Making diffraction data analysis and modelling easy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
