context:
  name: easydiffraction
  version: "0.5.5"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easydiffraction-${{ version }}.tar.gz
  sha256: 5a065a5a6b1366e634fe381868f8b8ef75f65c627cecd44f9fb0c854097dc2a0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - colorama
    - tabulate
    - asciichartpy
    - pooch
    - varname
    - asteval
    - scipy
    - sympy
    - lmfit
    - bumps
    - dfo-ls
    - gemmi
    - cryspy
    - diffpy.pdffit2
    - diffpy.utils
    - darkdetect

tests:
  - python:
      imports:
        - easydiffraction
      pip_check: false
      python_version: ${{ python_min }}.*

about:
  homepage: https://easydiffraction.org/
  summary: Making diffraction data analysis and modelling easy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
